FROM ubuntu:jammy

# Required else the ubuntu installation qill ask for timezone in interactive mode
ARG DEBIAN_FRONTEND=noninteractive;

# Need to fix acces to bin/sh for the node installer.
SHELL ["/bin/bash", "-c"]

# Requirement to be able to install any packages at all
RUN yes | apt-get update;

# Install some packages for easier work in docker
RUN     yes | apt-get install nano \
    &&  yes | apt-get install curl;

# Installing specific node version
RUN     touch ~/.bash_profile \
    &&  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash \
    &&  source ~/.nvm/nvm.sh \
    &&  nvm install v14.17.6;

# Need to expose internal container port to allow mapping it to some port that will be accesible outside of container
EXPOSE 3000 80 8080 5000

RUN ln -s /root/.nvm/versions/node/v14.17.6/bin/npm  /usr/bin/npm;
RUN ln -s /root/.nvm/versions/node/v14.17.6/bin/node /usr/bin/node;

# Solves issue with not being able to run globally installed npm packages
## This must be present alongside with export added in docker-compose for prod
ENV PATH="${PATH}:/root/.nvm/versions/node/v14.17.6/bin/"

# Things needed for prod
RUN npm i vite@2.6.14 @vitejs/plugin-react-refresh@1.3.6 vite-plugin-style-import@1.3.0 vite-plugin-html@2.1.1 path -g --unsafe-perm;
